_PhysicalSpecialSplit:: ; Determines if a move is Physical or Special
	ld a, [wTempMoveID]
	ld c,a
	ld b, $00
	ld hl,.MovesTable
	add hl,bc
	ld a,[hl]
	ld [wTempMoveID], a
	ret

.MovesTable
	db STATUS   ; NO_MOVE      ; 00
	db PHYSICAL ; POUND        ; 01
	db PHYSICAL ; KARATE_CHOP  ; 02
	db PHYSICAL ; DOUBLESLAP   ; 03
	db PHYSICAL ; COMET_PUNCH  ; 04
	db PHYSICAL ; MEGA_PUNCH   ; 05
	db PHYSICAL ; PAY_DAY      ; 06
	db PHYSICAL ; FIRE_PUNCH   ; 07
	db PHYSICAL ; ICE_PUNCH    ; 08
	db PHYSICAL ; THUNDERPUNCH ; 09
	db PHYSICAL ; SCRATCH      ; 0a
	db PHYSICAL ; VICEGRIP     ; 0b
	db PHYSICAL ; GUILLOTINE   ; 0c
	db SPECIAL  ; RAZOR_WIND   ; 0d
	db STATUS   ; SWORDS_DANCE ; 0e
	db PHYSICAL ; CUT          ; 0f
	db SPECIAL  ; GUST         ; 10
	db PHYSICAL ; WING_ATTACK  ; 11
	db STATUS   ; WHIRLWIND    ; 12
	db PHYSICAL ; FLY          ; 13
	db PHYSICAL ; BIND         ; 14
	db PHYSICAL ; SLAM         ; 15
	db PHYSICAL ; VINE_WHIP    ; 16
	db PHYSICAL ; STOMP        ; 17
	db PHYSICAL ; DOUBLE_KICK  ; 18
	db PHYSICAL ; MEGA_KICK    ; 19
	db PHYSICAL ; JUMP_KICK    ; 1a
	db PHYSICAL ; ROLLING_KICK ; 1b
	db STATUS   ; SAND_ATTACK  ; 1c
	db PHYSICAL ; HEADBUTT     ; 1d
	db PHYSICAL ; HORN_ATTACK  ; 1e
	db PHYSICAL ; FURY_ATTACK  ; 1f
	db PHYSICAL ; HORN_DRILL   ; 20
	db PHYSICAL ; TACKLE       ; 21
	db PHYSICAL ; BODY_SLAM    ; 22
	db PHYSICAL ; WRAP         ; 23
	db PHYSICAL ; TAKE_DOWN    ; 24
	db PHYSICAL ; THRASH       ; 25
	db PHYSICAL ; DOUBLE_EDGE  ; 26
	db STATUS   ; TAIL_WHIP    ; 27
	db PHYSICAL ; POISON_STING ; 28
	db PHYSICAL ; TWINEEDLE    ; 29
	db PHYSICAL ; PIN_MISSILE  ; 2a
	db STATUS   ; LEER         ; 2b
	db PHYSICAL ; BITE         ; 2c
	db STATUS   ; GROWL        ; 2d
	db STATUS   ; ROAR         ; 2e
	db STATUS   ; SING         ; 2f
	db STATUS   ; SUPERSONIC   ; 30
	db SPECIAL  ; SONICBOOM    ; 31
	db STATUS   ; DISABLE      ; 32
	db SPECIAL  ; ACID         ; 33
	db SPECIAL  ; EMBER        ; 34
	db SPECIAL  ; FLAMETHROWER ; 35
	db STATUS   ; MIST         ; 36
	db SPECIAL  ; WATER_GUN    ; 37
	db SPECIAL  ; HYDRO_PUMP   ; 38
	db SPECIAL  ; SURF         ; 39
	db SPECIAL  ; ICE_BEAM     ; 3a
	db SPECIAL  ; BLIZZARD     ; 3b
	db SPECIAL  ; PSYBEAM      ; 3c
	db SPECIAL  ; BUBBLEBEAM   ; 3d
	db SPECIAL  ; AURORA_BEAM  ; 3e
	db SPECIAL  ; HYPER_BEAM   ; 3f
	db PHYSICAL ; PECK         ; 40
	db PHYSICAL ; DRILL_PECK   ; 41
	db PHYSICAL ; SUBMISSION   ; 42
	db PHYSICAL ; LOW_KICK     ; 43
	db PHYSICAL ; COUNTER      ; 44
	db PHYSICAL ; SEISMIC_TOSS ; 45
	db PHYSICAL ; STRENGTH     ; 46
	db SPECIAL  ; ABSORB       ; 47
	db SPECIAL  ; MEGA_DRAIN   ; 48
	db STATUS   ; LEECH_SEED   ; 49
	db STATUS   ; GROWTH       ; 4a
	db PHYSICAL ; RAZOR_LEAF   ; 4b
	db SPECIAL  ; SOLARBEAM    ; 4c
	db STATUS   ; POISONPOWDER ; 4d
	db STATUS   ; STUN_SPORE   ; 4e
	db STATUS   ; SLEEP_POWDER ; 4f
	db SPECIAL  ; PETAL_DANCE  ; 50
	db STATUS   ; STRING_SHOT  ; 51
	db SPECIAL  ; DRAGON_RAGE  ; 52
	db SPECIAL  ; FIRE_SPIN    ; 53
	db SPECIAL  ; THUNDERSHOCK ; 54
	db SPECIAL  ; THUNDERBOLT  ; 55
	db STATUS   ; THUNDER_WAVE ; 56
	db SPECIAL  ; THUNDER      ; 57
	db PHYSICAL ; ROCK_THROW   ; 58
	db PHYSICAL ; EARTHQUAKE   ; 59
	db PHYSICAL ; FISSURE      ; 5a
	db PHYSICAL ; DIG          ; 5b
	db STATUS   ; TOXIC        ; 5c
	db SPECIAL  ; CONFUSION    ; 5d
	db SPECIAL  ; PSYCHIC_M    ; 5e
	db STATUS   ; HYPNOSIS     ; 5f
	db STATUS   ; MEDITATE     ; 60
	db STATUS   ; AGILITY      ; 61
	db PHYSICAL ; QUICK_ATTACK ; 62
	db PHYSICAL ; RAGE         ; 63
	db STATUS   ; TELEPORT     ; 64
	db SPECIAL  ; NIGHT_SHADE  ; 65
	db STATUS   ; MIMIC        ; 66
	db STATUS   ; SCREECH      ; 67
	db STATUS   ; DOUBLE_TEAM  ; 68
	db STATUS   ; RECOVER      ; 69
	db STATUS   ; HARDEN       ; 6a
	db STATUS   ; MINIMIZE     ; 6b
	db STATUS   ; SMOKESCREEN  ; 6c
	db STATUS   ; CONFUSE_RAY  ; 6d
	db STATUS   ; WITHDRAW     ; 6e
	db STATUS   ; DEFENSE_CURL ; 6f
	db STATUS   ; BARRIER      ; 70
	db STATUS   ; LIGHT_SCREEN ; 71
	db STATUS   ; HAZE         ; 72
	db STATUS   ; REFLECT      ; 73
	db STATUS   ; FOCUS_ENERGY ; 74
	db PHYSICAL ; BIDE         ; 75
	db STATUS   ; METRONOME    ; 76
	db STATUS   ; MIRROR_MOVE  ; 77
	db PHYSICAL ; SELFDESTRUCT ; 78
	db PHYSICAL ; EGG_BOMB     ; 79
	db PHYSICAL ; LICK         ; 7a
	db SPECIAL  ; SMOG         ; 7b
	db SPECIAL  ; SLUDGE       ; 7c
	db PHYSICAL ; BONE_CLUB    ; 7d
	db SPECIAL  ; FIRE_BLAST   ; 7e
	db PHYSICAL ; WATERFALL    ; 7f
	db PHYSICAL ; CLAMP        ; 80
	db SPECIAL  ; SWIFT        ; 81
	db PHYSICAL ; SKULL_BASH   ; 82
	db PHYSICAL ; SPIKE_CANNON ; 83
	db PHYSICAL ; CONSTRICT    ; 84
	db STATUS   ; AMNESIA      ; 85
	db STATUS   ; KINESIS      ; 86
	db STATUS   ; SOFTBOILED   ; 87
	db PHYSICAL ; HI_JUMP_KICK ; 88
	db STATUS   ; GLARE        ; 89
	db SPECIAL  ; DREAM_EATER  ; 8a
	db STATUS   ; POISON_GAS   ; 8b
	db PHYSICAL ; BARRAGE      ; 8c
	db PHYSICAL ; LEECH_LIFE   ; 8d
	db STATUS   ; LOVELY_KISS  ; 8e
	db PHYSICAL ; SKY_ATTACK   ; 8f
	db STATUS   ; TRANSFORM    ; 90
	db SPECIAL  ; BUBBLE       ; 91
	db PHYSICAL ; DIZZY_PUNCH  ; 92
	db STATUS   ; SPORE        ; 93
	db STATUS   ; FLASH        ; 94
	db SPECIAL  ; PSYWAVE      ; 95
	db STATUS   ; SPLASH       ; 96
	db STATUS   ; ACID_ARMOR   ; 97
	db PHYSICAL ; CRABHAMMER   ; 98
	db PHYSICAL ; EXPLOSION    ; 99
	db PHYSICAL ; FURY_SWIPES  ; 9a
	db PHYSICAL ; BONEMERANG   ; 9b
	db STATUS   ; REST         ; 9c
	db PHYSICAL ; ROCK_SLIDE   ; 9d
	db PHYSICAL ; HYPER_FANG   ; 9e
	db STATUS   ; SHARPEN      ; 9f
	db STATUS   ; CONVERSION   ; a0
	db SPECIAL  ; TRI_ATTACK   ; a1
	db PHYSICAL ; SUPER_FANG   ; a2
	db PHYSICAL ; SLASH        ; a3
	db STATUS   ; SUBSTITUTE   ; a4
	db PHYSICAL ; STRUGGLE     ; a5
	db PHYSICAL ; FEINT_ATTACK ; a6
	db SPECIAL  ; SLUDGE_BOMB  ; a7
	db PHYSICAL ; FLAME_WHEEL  ; a8
	db PHYSICAL ; OUTRAGE      ; a9
	db PHYSICAL ; SACRED_FIRE  ; aa
	db SPECIAL  ; DRAGON_BREATH; ab
	db SPECIAL  ; SHADOW_BALL  ; ac
	db PHYSICAL ; CRUNCH       ; ad
	db PHYSICAL ; EXTREME_SPEED; ae
	db SPECIAL  ; GIGA_DRAIN   ; af
	db SPECIAL  ; HYPER_VOICE  ; b0
	db PHYSICAL ; LEAF_BLADE   ; b1
	db PHYSICAL ; IRON_HEAD    ; b2
	db SPECIAL  ; FLASH_CANNON ; b3
	db SPECIAL  ; AURA_SPHERE  ; b4
	db PHYSICAL ; DRAIN_PUNCH  ; b5
	db SPECIAL  ; AIR_SLASH    ; b6
	db SPECIAL  ; EARTH_POWER  ; b7
	db PHYSICAL ; POISON_JAB   ; b8
	db SPECIAL  ; POWER_GEM    ; b9
	db SPECIAL  ; BUG_BUZZ     ; ba
	db SPECIAL  ; DARK_PULSE   ; bb
	db SPECIAL  ; DRAGON_PULSE ; bc
	db SPECIAL  ; MOONBLAST    ; bd
	db PHYSICAL ; PLAY_ROUGH   ; be
	db PHYSICAL ; SHADOW_BONE  ; bf
	